-- liquibase formatted sql

-- changeset pjanik:create-tables-mysql dbms:mysql
CREATE TABLE countries (
                           id BIGINT NOT NULL AUTO_INCREMENT,
                           name VARCHAR(255),
                           PRIMARY KEY (id));

-- rollback DROP TABLE countries;

-- changeset pjanik:create-tables-hsqldb dbms:hsqldb
CREATE TABLE countries (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           name VARCHAR(255),
                           PRIMARY KEY (id));

-- rollback DROP TABLE countries;