-- liquibase formatted sql

-- changeset pjanik:create-tables-mysql dbms:mysql
CREATE TABLE countries (
                           id BIGINT NOT NULL AUTO_INCREMENT,
                           name VARCHAR(255),
                           PRIMARY KEY (id));

CREATE TABLE actors (
                        id BIGINT NOT NULL AUTO_INCREMENT,
                        name VARCHAR(255),
                        country_id BIGINT,
                        PRIMARY KEY (id),
                        FOREIGN KEY (country_id) REFERENCES countries (id));

CREATE TABLE movies (
                        id BIGINT NOT NULL AUTO_INCREMENT,
                        title VARCHAR(255),
                        PRIMARY KEY (id));

CREATE TABLE movies_actors (
                               movie_id BIGINT NOT NULL,
                               actor_id BIGINT NOT NULL,
                               PRIMARY KEY (movie_id, actor_id),
                               FOREIGN KEY (movie_id) REFERENCES movies (id),
                               FOREIGN KEY (actor_id) REFERENCES actors (id));

-- rollback DROP TABLE movies_actors;
-- rollback DROP TABLE movies;
-- rollback DROP TABLE actors;
-- rollback DROP TABLE countries;

-- changeset pjanik:create-tables-hsqldb dbms:hsqldb
CREATE TABLE countries (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           name VARCHAR(255),
                           PRIMARY KEY (id));

CREATE TABLE actors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        name VARCHAR(255),
                        country_id BIGINT,
                        PRIMARY KEY (id),
                        FOREIGN KEY (country_id) REFERENCES countries (id));

CREATE TABLE movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        title VARCHAR(255),
                        PRIMARY KEY (id));

CREATE TABLE movies_actors (
                               movie_id BIGINT NOT NULL,
                               actor_id BIGINT NOT NULL,
                               PRIMARY KEY (movie_id, actor_id),
                               FOREIGN KEY (movie_id) REFERENCES movies (id),
                               FOREIGN KEY (actor_id) REFERENCES actors (id));

-- rollback DROP TABLE movies_actors;
-- rollback DROP TABLE movies;
-- rollback DROP TABLE actors;
-- rollback DROP TABLE countries;