-- liquibase formatted sql

-- changeset pjanik:create-tables-mysql dbms:mysql

CREATE TABLE movies (
                        id BIGINT NOT NULL AUTO_INCREMENT,
                        title VARCHAR(255),
                        PRIMARY KEY (id));

CREATE TABLE movies_actors (
                               movie_id BIGINT NOT NULL,
                               actor_id BIGINT NOT NULL,
                               PRIMARY KEY (movie_id, actor_id),
                               FOREIGN KEY (movie_id) REFERENCES movies (id),
                               FOREIGN KEY (actor_id) REFERENCES actors (id));

-- rollback DROP TABLE movies;
-- rollback DROP TABLE movies_actors;

-- changeset pjanik:create-tables-hsqldb dbms:hsqldb
CREATE TABLE movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        title VARCHAR(255),
                        PRIMARY KEY (id));

CREATE TABLE movies_actors (
                               movie_id BIGINT NOT NULL,
                               actor_id BIGINT NOT NULL,
                               PRIMARY KEY (movie_id, actor_id),
                               FOREIGN KEY (movie_id) REFERENCES movies (id),
                               FOREIGN KEY (actor_id) REFERENCES actors (id));

-- rollback DROP TABLE movies;
-- rollback DROP TABLE movies_actors;
