-- liquibase formatted sql

-- changeset pjanik:create-tables-mysql dbms:mysql

CREATE TABLE actors (
                        id BIGINT NOT NULL AUTO_INCREMENT,
                        name VARCHAR(255),
                        country_id BIGINT,
                        PRIMARY KEY (id),
                        FOREIGN KEY (country_id) REFERENCES countries (id));

-- rollback DROP TABLE actors;

-- changeset pjanik:create-tables-hsqldb dbms:hsqldb

CREATE TABLE actors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        name VARCHAR(255),
                        country_id BIGINT,
                        PRIMARY KEY (id),
                        FOREIGN KEY (country_id) REFERENCES countries (id));

-- rollback DROP TABLE actors;
